### ISSUE TITLE
mixed content

### ISSUE THREAD

**Issue by voogarix** [dbeley/gsmarena-scraper#2]
hello again. thanks for quick fix. but there is another problem. parser do not saves each data under required column. 

you can see an example [https://imgur.com/a/Pna0RkW](url)

**Comment by dbeley** [comment]
Hello I think you took the comma character (',') to separate the fields. Can you try to import the csv file and to make sure you only use semi-colon (';') as the separator ?

**Comment by voogarix** [comment]
> 
> 
> Hello I think you took the comma character (',') to separate the fields. Can you try to import the csv file and to make sure you only use semi-colon (';') as the separator ?

You are right. with semicolon everything is good. last thing, can you make possible to check whether brand csv file exists in directory? because everytime it starts from 0 and scrape all data. Or can you make possible to scrape by brand?

**Comment by dbeley** [comment]
Good idea, I have pushed a new version where it doesn't start the extraction but reads the file if a csv file for a brand already exists (allowing to choose a brand is also a good idea but it might be more difficult so I'm lefting that out for now).

**Comment by voogarix** [comment]
> 
> 
> Good idea, I have pushed a new version where it doesn't start the extraction but reads the file if a csv file for a brand already exists (allowing to choose a brand is also a good idea but it might be more difficult so I'm lefting that out for now).

Perfect. Thanks for quick fixes.
