### ISSUE TITLE
How to avoid being banned?

### ISSUE THREAD

**Issue by remivigan** [dbeley/gsmarena-scraper#3]
Hey dbeley,

What do you suggest to do to avoid being banned while scrapping?

**Comment by dbeley** [comment]
Hello yeah it seems gsmarena has changed their policy on web requests so unfortunately you're very quickly banned if using my script.

I've tried the usual things (changing the header, adding some delay between requests) but no luck on my end :disappointed: .

(btw it seems the ban lasts a day or so).

**Comment by dbeley** [comment]
Hi the project is now using a tor proxy running in a docker container, which works quite fine. It's a more complicated process than before, but I'm afraid there are no easier way to do this.

 I'm closing the issue for now, feel free to reopen it!
